VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "HostRanking"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'--------------------------------------------------------------------------------
'
' 端末ブロックランキング集計用
'
'--------------------------------------------------------------------------------

''' <summary>
''' ホスト名
''' </summary>
''' <remarks></remarks>
Public Host As String

''' <summary>
''' ブロック数
''' </summary>
''' <remarks></remarks>
Public Count As Long
